# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'prueba_appcenter_codepush' do
  pod 'AppCenter/Crashes', '~> 1.12.0'
  pod 'AppCenter/Analytics', '~> 1.12.0'
  pod 'AppCenterReactNativeShared', '~> 1.11.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for prueba_appcenter_codepush

  

  platform :ios, '9.0'
  target 'prueba_appcenter_codepushTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'prueba_appcenter_codepush-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for prueba_appcenter_codepush-tvOS

  target 'prueba_appcenter_codepush-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
